version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      all-actions:
        patterns: ["*"]
    labels:
      - "dependencies"
      - "github-actions"
      - "auto-merge"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      all-docker:
        patterns: ["*"]
    labels:
      - "dependencies"
      - "auto-merge"
    commit-message:
      prefix: "chore"
      include: "scope"
