services:
  claude:
    image: ghcr.io/claude-contrib/claude-sandbox:${CLAUDE_DOCKER_TAG}
    working_dir: ${CLAUDE_HOST_WORKING_DIR}
    volumes:
      - claude-nix:/nix
      - claude-local:${CLAUDE_HOST_HOME}/.local
      - claude-cache:${CLAUDE_HOST_HOME}/.cache
      - ${CLAUDE_HOST_CONFIG_DIR}:${CLAUDE_HOST_CONFIG_DIR}:ro
      - ${CLAUDE_HOST_WORKING_DIR}:${CLAUDE_HOST_WORKING_DIR}
      - ${CLAUDE_CONFIG_DIR}:${CLAUDE_CONFIG_DIR}
    environment:
      - CLAUDE_HOST_USER
      - CLAUDE_HOST_UID
      - CLAUDE_HOST_GID
      - CLAUDE_HOST_HOME

volumes:
  claude-nix:
    name: claude-nix
  claude-local:
    name: claude-local
  claude-cache:
    name: claude-cache
